ci: add preview for gh-pages to each PR (#1044)

diff --git a/.github/workflows/unittests.yaml b/.github/workflows/unittests.yaml
--- a/.github/workflows/unittests.yaml
+++ b/.github/workflows/unittests.yaml
@@ -2,13 +2,18 @@ name: unit tests
 
 on: [push, pull_request]
 
+concurrency:
+  group: docs-${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   test:
+    name: Unit Tests
     runs-on: ubuntu-24.04
     environment: github-actions
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
           lfs: true
@@ -59,3 +64,87 @@ jobs:
       - name: Upload to Sonatype
         run: |
           sbt +publish
+  docs:
+    name: Generate tool and metric markdown docs
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          # To work with the `pull_request` or any other non-`push` even with git-auto-commit
+          ref: ${{ github.head_ref }}
+      - name: Checkout gh-pages
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          lfs: true
+          ref: gh-pages
+          path: build
+      # Note: we use sdkman to install java and scala as other actions do not provide support for
+      # Java 8 and scaladoc
+      - name: Setup sdkman
+        shell: bash -l {0}
+        run: |
+          curl -s "https://get.sdkman.io" | bash
+          source "$HOME/.sdkman/bin/sdkman-init.sh"
+          sdk version
+          echo 'source "$HOME/.sdkman/bin/sdkman-init.sh"' >> "$HOME/.bash_profile"
+      - name: Install tools
+        shell: bash -l {0}
+        run: |
+          sdk install java 8.312.07.1-amzn
+          sdk install scala 2.13.0
+          sdk install sbt 1.10.4
+      - name: Cache .ivy2
+        uses: actions/cache@v4
+        with:
+          path: ~/.ivy2
+          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
+      - name: Cache .sbt
+        uses: actions/cache@v4
+        with:
+          path: ~/.sbt
+          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.properties') }}
+      - name: Get fgbio version
+        shell: bash -l {0}
+        run: |
+          FGBIO_VERSION=$(sbt -Dsbt.supershell=false --no-colors --error 'print ThisBuild / version' | tail -n 1)
+          if [ "${FGBIO_VERSION}" == "" ]; then
+            echo "Error: FGBIO_VERSION was empty"
+            exit 1
+          fi
+          echo "fgbio version: ${FGBIO_VERSION}"
+          echo "FGBIO_VERSION=${FGBIO_VERSION}" >> $GITHUB_ENV
+      - name: Build assembly JAR
+        shell: bash -l {0}
+        run: |
+          sbt +assembly
+      - name: Build tool docs
+        shell: bash -l {0}
+        run: |
+          mkdir -p build/tools/${FGBIO_VERSION}
+          java -cp target/scala-2.13/fgbio-*.jar com.fulcrumgenomics.internal.InternalTools BuildToolDocs -o build/tools/${FGBIO_VERSION}
+          pushd build/tools 
+          rm latest 
+          ln -s ${FGBIO_VERSION} latest
+          popd
+      - name: Build metric docs
+        shell: bash -l {0}
+        run: |
+          mkdir -p build/metrics/${FGBIO_VERSION}
+          bash run_metrics_doclet.sh
+          mv -v target/metrics.md build/metrics/${FGBIO_VERSION}/index.md
+          pushd build/metrics
+          rm latest 
+          ln -s ${FGBIO_VERSION} latest
+          popd
+      - name: Update JAR version in index.md
+        shell: bash -l {0}
+        run: |
+          sed -i -e 's_fgbio-.*.jar_fgbio-'${FGBIO_VERSION}'.jar_g' build/index.md
+      - name: Generate gh-pages preview
+        uses: rossjrw/pr-preview-action@df22037db54ab6ee34d3c1e2b8810ac040a530c6 # v1.6.0
+        with:
+          source-dir: ./build/
